version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
